# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Lucas\PycharmProjects\BeamProject\beampy\beamPyUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1239, 800)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.main_gl = QtGui.QGridLayout()
        self.main_gl.setObjectName(_fromUtf8("main_gl"))
        self.beam_draw_widget = QtGui.QWidget(self.centralwidget)
        self.beam_draw_widget.setObjectName(_fromUtf8("beam_draw_widget"))
        self.beam_draw_widget_vl = QtGui.QVBoxLayout(self.beam_draw_widget)
        self.beam_draw_widget_vl.setMargin(0)
        self.beam_draw_widget_vl.setObjectName(_fromUtf8("beam_draw_widget_vl"))
        self.main_gl.addWidget(self.beam_draw_widget, 0, 0, 1, 3)
        self.beam_widget = QtGui.QWidget(self.centralwidget)
        self.beam_widget.setMaximumSize(QtCore.QSize(16777215, 120))
        self.beam_widget.setObjectName(_fromUtf8("beam_widget"))
        self.beam_widget_vl = QtGui.QVBoxLayout(self.beam_widget)
        self.beam_widget_vl.setMargin(0)
        self.beam_widget_vl.setSpacing(0)
        self.beam_widget_vl.setObjectName(_fromUtf8("beam_widget_vl"))
        self.main_gl.addWidget(self.beam_widget, 3, 1, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.message_lbl = QtGui.QLabel(self.centralwidget)
        self.message_lbl.setObjectName(_fromUtf8("message_lbl"))
        self.gridLayout.addWidget(self.message_lbl, 0, 1, 1, 1)
        self.lbl_message = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_message.sizePolicy().hasHeightForWidth())
        self.lbl_message.setSizePolicy(sizePolicy)
        self.lbl_message.setObjectName(_fromUtf8("lbl_message"))
        self.gridLayout.addWidget(self.lbl_message, 0, 0, 1, 1)
        self.main_gl.addLayout(self.gridLayout, 2, 1, 1, 1)
        self.properties_supports_vl = QtGui.QGridLayout()
        self.properties_supports_vl.setObjectName(_fromUtf8("properties_supports_vl"))
        self.calculate_beam = QtGui.QPushButton(self.centralwidget)
        self.calculate_beam.setObjectName(_fromUtf8("calculate_beam"))
        self.properties_supports_vl.addWidget(self.calculate_beam, 3, 0, 1, 1)
        self.beam_properties_gb = QtGui.QGroupBox(self.centralwidget)
        self.beam_properties_gb.setObjectName(_fromUtf8("beam_properties_gb"))
        self.beam_properties_gb_vl = QtGui.QGridLayout(self.beam_properties_gb)
        self.beam_properties_gb_vl.setObjectName(_fromUtf8("beam_properties_gb_vl"))
        self.base_dspn = QtGui.QDoubleSpinBox(self.beam_properties_gb)
        self.base_dspn.setDecimals(4)
        self.base_dspn.setMinimum(0.0001)
        self.base_dspn.setMaximum(9999.0)
        self.base_dspn.setProperty("value", 1.0)
        self.base_dspn.setObjectName(_fromUtf8("base_dspn"))
        self.beam_properties_gb_vl.addWidget(self.base_dspn, 10, 1, 1, 2)
        self.pushButton = QtGui.QPushButton(self.beam_properties_gb)
        self.pushButton.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(False)
        self.pushButton.setAutoExclusive(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.buttonGroup_2 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.pushButton)
        self.beam_properties_gb_vl.addWidget(self.pushButton, 11, 1, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.beam_properties_gb)
        self.pushButton_3.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setChecked(False)
        self.pushButton_3.setAutoExclusive(True)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.buttonGroup_2.addButton(self.pushButton_3)
        self.beam_properties_gb_vl.addWidget(self.pushButton_3, 11, 2, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.beam_properties_gb)
        self.pushButton_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setChecked(True)
        self.pushButton_2.setAutoExclusive(True)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.buttonGroup_2.addButton(self.pushButton_2)
        self.beam_properties_gb_vl.addWidget(self.pushButton_2, 11, 0, 1, 1)
        self.lbl_length = QtGui.QLabel(self.beam_properties_gb)
        self.lbl_length.setObjectName(_fromUtf8("lbl_length"))
        self.beam_properties_gb_vl.addWidget(self.lbl_length, 1, 0, 1, 1)
        self.lbl_young_module = QtGui.QLabel(self.beam_properties_gb)
        self.lbl_young_module.setObjectName(_fromUtf8("lbl_young_module"))
        self.beam_properties_gb_vl.addWidget(self.lbl_young_module, 0, 0, 1, 1)
        self.length_dspn = QtGui.QDoubleSpinBox(self.beam_properties_gb)
        self.length_dspn.setDecimals(4)
        self.length_dspn.setMinimum(0.0001)
        self.length_dspn.setMaximum(9999.0)
        self.length_dspn.setProperty("value", 10.0)
        self.length_dspn.setObjectName(_fromUtf8("length_dspn"))
        self.beam_properties_gb_vl.addWidget(self.length_dspn, 1, 1, 1, 2)
        self.young_module_dpsn = QtGui.QDoubleSpinBox(self.beam_properties_gb)
        self.young_module_dpsn.setMinimum(1.0)
        self.young_module_dpsn.setMaximum(99999.0)
        self.young_module_dpsn.setSingleStep(10.0)
        self.young_module_dpsn.setProperty("value", 200.0)
        self.young_module_dpsn.setObjectName(_fromUtf8("young_module_dpsn"))
        self.beam_properties_gb_vl.addWidget(self.young_module_dpsn, 0, 1, 1, 2)
        self.height_dpsn = QtGui.QDoubleSpinBox(self.beam_properties_gb)
        self.height_dpsn.setDecimals(4)
        self.height_dpsn.setMinimum(0.0001)
        self.height_dpsn.setMaximum(9999.0)
        self.height_dpsn.setProperty("value", 2.0)
        self.height_dpsn.setObjectName(_fromUtf8("height_dpsn"))
        self.beam_properties_gb_vl.addWidget(self.height_dpsn, 9, 1, 1, 2)
        self.lbl_inertia_moment = QtGui.QLabel(self.beam_properties_gb)
        self.lbl_inertia_moment.setEnabled(True)
        self.lbl_inertia_moment.setObjectName(_fromUtf8("lbl_inertia_moment"))
        self.beam_properties_gb_vl.addWidget(self.lbl_inertia_moment, 12, 0, 1, 1)
        self.lbl_height = QtGui.QLabel(self.beam_properties_gb)
        self.lbl_height.setObjectName(_fromUtf8("lbl_height"))
        self.beam_properties_gb_vl.addWidget(self.lbl_height, 9, 0, 1, 1)
        self.lbl_length_2 = QtGui.QLabel(self.beam_properties_gb)
        self.lbl_length_2.setObjectName(_fromUtf8("lbl_length_2"))
        self.beam_properties_gb_vl.addWidget(self.lbl_length_2, 10, 0, 1, 1)
        self.inertia_moment_dspn = QtGui.QLineEdit(self.beam_properties_gb)
        self.inertia_moment_dspn.setReadOnly(True)
        self.inertia_moment_dspn.setObjectName(_fromUtf8("inertia_moment_dspn"))
        self.beam_properties_gb_vl.addWidget(self.inertia_moment_dspn, 12, 1, 1, 2)
        self.properties_supports_vl.addWidget(self.beam_properties_gb, 1, 0, 1, 1)
        self.supports_gb = QtGui.QGroupBox(self.centralwidget)
        self.supports_gb.setObjectName(_fromUtf8("supports_gb"))
        self.supports_gb_gl = QtGui.QGridLayout(self.supports_gb)
        self.supports_gb_gl.setObjectName(_fromUtf8("supports_gb_gl"))
        self.supports_combo = QtGui.QComboBox(self.supports_gb)
        self.supports_combo.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.supports_combo.setEditable(True)
        self.supports_combo.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.supports_combo.setDuplicatesEnabled(False)
        self.supports_combo.setObjectName(_fromUtf8("supports_combo"))
        self.supports_gb_gl.addWidget(self.supports_combo, 3, 0, 1, 1)
        self.left_support_combo = QtGui.QComboBox(self.supports_gb)
        self.left_support_combo.setObjectName(_fromUtf8("left_support_combo"))
        self.left_support_combo.addItem(_fromUtf8(""))
        self.left_support_combo.addItem(_fromUtf8(""))
        self.left_support_combo.addItem(_fromUtf8(""))
        self.supports_gb_gl.addWidget(self.left_support_combo, 1, 0, 1, 1)
        self.lbl_right_support = QtGui.QLabel(self.supports_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_right_support.sizePolicy().hasHeightForWidth())
        self.lbl_right_support.setSizePolicy(sizePolicy)
        self.lbl_right_support.setObjectName(_fromUtf8("lbl_right_support"))
        self.supports_gb_gl.addWidget(self.lbl_right_support, 0, 1, 1, 1)
        self.right_support_combo = QtGui.QComboBox(self.supports_gb)
        self.right_support_combo.setObjectName(_fromUtf8("right_support_combo"))
        self.right_support_combo.addItem(_fromUtf8(""))
        self.right_support_combo.addItem(_fromUtf8(""))
        self.right_support_combo.addItem(_fromUtf8(""))
        self.supports_gb_gl.addWidget(self.right_support_combo, 1, 1, 1, 1)
        self.lbl_add_support_2 = QtGui.QLabel(self.supports_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_add_support_2.sizePolicy().hasHeightForWidth())
        self.lbl_add_support_2.setSizePolicy(sizePolicy)
        self.lbl_add_support_2.setObjectName(_fromUtf8("lbl_add_support_2"))
        self.supports_gb_gl.addWidget(self.lbl_add_support_2, 2, 1, 1, 1)
        self.hinges_combo = QtGui.QComboBox(self.supports_gb)
        self.hinges_combo.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.hinges_combo.setEditable(True)
        self.hinges_combo.setDuplicatesEnabled(False)
        self.hinges_combo.setObjectName(_fromUtf8("hinges_combo"))
        self.supports_gb_gl.addWidget(self.hinges_combo, 3, 1, 1, 1)
        self.remove_hinge_btn = QtGui.QPushButton(self.supports_gb)
        self.remove_hinge_btn.setObjectName(_fromUtf8("remove_hinge_btn"))
        self.supports_gb_gl.addWidget(self.remove_hinge_btn, 4, 1, 1, 1)
        self.lbl_left_support = QtGui.QLabel(self.supports_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_left_support.sizePolicy().hasHeightForWidth())
        self.lbl_left_support.setSizePolicy(sizePolicy)
        self.lbl_left_support.setObjectName(_fromUtf8("lbl_left_support"))
        self.supports_gb_gl.addWidget(self.lbl_left_support, 0, 0, 1, 1)
        self.lbl_add_support = QtGui.QLabel(self.supports_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_add_support.sizePolicy().hasHeightForWidth())
        self.lbl_add_support.setSizePolicy(sizePolicy)
        self.lbl_add_support.setObjectName(_fromUtf8("lbl_add_support"))
        self.supports_gb_gl.addWidget(self.lbl_add_support, 2, 0, 1, 1)
        self.remove_support_btn = QtGui.QPushButton(self.supports_gb)
        self.remove_support_btn.setObjectName(_fromUtf8("remove_support_btn"))
        self.supports_gb_gl.addWidget(self.remove_support_btn, 4, 0, 1, 1)
        self.properties_supports_vl.addWidget(self.supports_gb, 2, 0, 1, 1)
        self.main_gl.addLayout(self.properties_supports_vl, 2, 0, 5, 1)
        self.add_remove_hl = QtGui.QHBoxLayout()
        self.add_remove_hl.setObjectName(_fromUtf8("add_remove_hl"))
        self.add_load_btn = QtGui.QPushButton(self.centralwidget)
        self.add_load_btn.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.add_load_btn.setObjectName(_fromUtf8("add_load_btn"))
        self.add_remove_hl.addWidget(self.add_load_btn)
        self.remove_load_btn = QtGui.QPushButton(self.centralwidget)
        self.remove_load_btn.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.remove_load_btn.setObjectName(_fromUtf8("remove_load_btn"))
        self.add_remove_hl.addWidget(self.remove_load_btn)
        self.main_gl.addLayout(self.add_remove_hl, 6, 2, 1, 1)
        self.load_treeview = QtGui.QTreeView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_treeview.sizePolicy().hasHeightForWidth())
        self.load_treeview.setSizePolicy(sizePolicy)
        self.load_treeview.setMinimumSize(QtCore.QSize(370, 0))
        self.load_treeview.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.load_treeview.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.load_treeview.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.load_treeview.setAutoScroll(True)
        self.load_treeview.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.load_treeview.setAlternatingRowColors(True)
        self.load_treeview.setObjectName(_fromUtf8("load_treeview"))
        self.main_gl.addWidget(self.load_treeview, 4, 1, 3, 1)
        self.loads_tab = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loads_tab.sizePolicy().hasHeightForWidth())
        self.loads_tab.setSizePolicy(sizePolicy)
        self.loads_tab.setObjectName(_fromUtf8("loads_tab"))
        self.pnt_load_tab_widget = QtGui.QWidget()
        self.pnt_load_tab_widget.setObjectName(_fromUtf8("pnt_load_tab_widget"))
        self.pnt_load_tab_widget_gl_4 = QtGui.QGridLayout(self.pnt_load_tab_widget)
        self.pnt_load_tab_widget_gl_4.setHorizontalSpacing(0)
        self.pnt_load_tab_widget_gl_4.setObjectName(_fromUtf8("pnt_load_tab_widget_gl_4"))
        self.lbl_point_load_mag = QtGui.QLabel(self.pnt_load_tab_widget)
        self.lbl_point_load_mag.setObjectName(_fromUtf8("lbl_point_load_mag"))
        self.pnt_load_tab_widget_gl_4.addWidget(self.lbl_point_load_mag, 2, 0, 1, 1)
        self.lbl_point_load_pos = QtGui.QLabel(self.pnt_load_tab_widget)
        self.lbl_point_load_pos.setObjectName(_fromUtf8("lbl_point_load_pos"))
        self.pnt_load_tab_widget_gl_4.addWidget(self.lbl_point_load_pos, 3, 0, 1, 1)
        self.pnt_load_up_chkbtn = QtGui.QPushButton(self.pnt_load_tab_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pnt_load_up_chkbtn.sizePolicy().hasHeightForWidth())
        self.pnt_load_up_chkbtn.setSizePolicy(sizePolicy)
        self.pnt_load_up_chkbtn.setMinimumSize(QtCore.QSize(100, 100))
        self.pnt_load_up_chkbtn.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.pnt_load_up_chkbtn.setFont(font)
        self.pnt_load_up_chkbtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pnt_load_up_chkbtn.setCheckable(True)
        self.pnt_load_up_chkbtn.setAutoExclusive(True)
        self.pnt_load_up_chkbtn.setObjectName(_fromUtf8("pnt_load_up_chkbtn"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.pnt_load_up_chkbtn)
        self.pnt_load_tab_widget_gl_4.addWidget(self.pnt_load_up_chkbtn, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.pnt_load_tab_widget_gl_4.addItem(spacerItem, 1, 0, 1, 2)
        self.pnt_load_mag_dpsn = QtGui.QDoubleSpinBox(self.pnt_load_tab_widget)
        self.pnt_load_mag_dpsn.setDecimals(2)
        self.pnt_load_mag_dpsn.setMinimum(0.0)
        self.pnt_load_mag_dpsn.setMaximum(999999999.0)
        self.pnt_load_mag_dpsn.setProperty("value", 5.0)
        self.pnt_load_mag_dpsn.setObjectName(_fromUtf8("pnt_load_mag_dpsn"))
        self.pnt_load_tab_widget_gl_4.addWidget(self.pnt_load_mag_dpsn, 2, 1, 1, 1)
        self.pnt_load_pos_dpsn = QtGui.QDoubleSpinBox(self.pnt_load_tab_widget)
        self.pnt_load_pos_dpsn.setMaximum(999999999.0)
        self.pnt_load_pos_dpsn.setProperty("value", 5.0)
        self.pnt_load_pos_dpsn.setObjectName(_fromUtf8("pnt_load_pos_dpsn"))
        self.pnt_load_tab_widget_gl_4.addWidget(self.pnt_load_pos_dpsn, 3, 1, 1, 1)
        self.pnt_load_down_chkbtn = QtGui.QPushButton(self.pnt_load_tab_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pnt_load_down_chkbtn.sizePolicy().hasHeightForWidth())
        self.pnt_load_down_chkbtn.setSizePolicy(sizePolicy)
        self.pnt_load_down_chkbtn.setMinimumSize(QtCore.QSize(100, 100))
        self.pnt_load_down_chkbtn.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pnt_load_down_chkbtn.setFont(font)
        self.pnt_load_down_chkbtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pnt_load_down_chkbtn.setCheckable(True)
        self.pnt_load_down_chkbtn.setChecked(True)
        self.pnt_load_down_chkbtn.setAutoExclusive(True)
        self.pnt_load_down_chkbtn.setObjectName(_fromUtf8("pnt_load_down_chkbtn"))
        self.buttonGroup.addButton(self.pnt_load_down_chkbtn)
        self.pnt_load_tab_widget_gl_4.addWidget(self.pnt_load_down_chkbtn, 0, 1, 1, 1)
        self.loads_tab.addTab(self.pnt_load_tab_widget, _fromUtf8(""))
        self.moment_tab_widget = QtGui.QWidget()
        self.moment_tab_widget.setObjectName(_fromUtf8("moment_tab_widget"))
        self.pnt_load_tab_widget_gl = QtGui.QGridLayout(self.moment_tab_widget)
        self.pnt_load_tab_widget_gl.setHorizontalSpacing(0)
        self.pnt_load_tab_widget_gl.setObjectName(_fromUtf8("pnt_load_tab_widget_gl"))
        self.moment_pos_dpsn = QtGui.QDoubleSpinBox(self.moment_tab_widget)
        self.moment_pos_dpsn.setMaximum(999999999.0)
        self.moment_pos_dpsn.setProperty("value", 7.0)
        self.moment_pos_dpsn.setObjectName(_fromUtf8("moment_pos_dpsn"))
        self.pnt_load_tab_widget_gl.addWidget(self.moment_pos_dpsn, 4, 1, 1, 1)
        self.lbl_moment_pos = QtGui.QLabel(self.moment_tab_widget)
        self.lbl_moment_pos.setObjectName(_fromUtf8("lbl_moment_pos"))
        self.pnt_load_tab_widget_gl.addWidget(self.lbl_moment_pos, 3, 0, 1, 1)
        self.lbl_moment_mag = QtGui.QLabel(self.moment_tab_widget)
        self.lbl_moment_mag.setObjectName(_fromUtf8("lbl_moment_mag"))
        self.pnt_load_tab_widget_gl.addWidget(self.lbl_moment_mag, 4, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.pnt_load_tab_widget_gl.addItem(spacerItem1, 1, 0, 1, 2)
        self.moment_mag_dpsn = QtGui.QDoubleSpinBox(self.moment_tab_widget)
        self.moment_mag_dpsn.setMaximum(999999999.0)
        self.moment_mag_dpsn.setProperty("value", 7.0)
        self.moment_mag_dpsn.setObjectName(_fromUtf8("moment_mag_dpsn"))
        self.pnt_load_tab_widget_gl.addWidget(self.moment_mag_dpsn, 3, 1, 1, 1)
        self.moment_ccw_chkbtn = QtGui.QPushButton(self.moment_tab_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moment_ccw_chkbtn.sizePolicy().hasHeightForWidth())
        self.moment_ccw_chkbtn.setSizePolicy(sizePolicy)
        self.moment_ccw_chkbtn.setMinimumSize(QtCore.QSize(50, 50))
        self.moment_ccw_chkbtn.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(False)
        font.setWeight(50)
        self.moment_ccw_chkbtn.setFont(font)
        self.moment_ccw_chkbtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.moment_ccw_chkbtn.setStatusTip(_fromUtf8(""))
        self.moment_ccw_chkbtn.setCheckable(True)
        self.moment_ccw_chkbtn.setAutoExclusive(True)
        self.moment_ccw_chkbtn.setObjectName(_fromUtf8("moment_ccw_chkbtn"))
        self.pnt_load_tab_widget_gl.addWidget(self.moment_ccw_chkbtn, 0, 0, 1, 1)
        self.moment_cw_chkbtn = QtGui.QPushButton(self.moment_tab_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moment_cw_chkbtn.sizePolicy().hasHeightForWidth())
        self.moment_cw_chkbtn.setSizePolicy(sizePolicy)
        self.moment_cw_chkbtn.setMinimumSize(QtCore.QSize(100, 100))
        self.moment_cw_chkbtn.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.moment_cw_chkbtn.setFont(font)
        self.moment_cw_chkbtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.moment_cw_chkbtn.setStatusTip(_fromUtf8(""))
        self.moment_cw_chkbtn.setCheckable(True)
        self.moment_cw_chkbtn.setChecked(True)
        self.moment_cw_chkbtn.setAutoExclusive(True)
        self.moment_cw_chkbtn.setObjectName(_fromUtf8("moment_cw_chkbtn"))
        self.pnt_load_tab_widget_gl.addWidget(self.moment_cw_chkbtn, 0, 1, 1, 1)
        self.loads_tab.addTab(self.moment_tab_widget, _fromUtf8(""))
        self.distr_load_tab_widget = QtGui.QWidget()
        self.distr_load_tab_widget.setObjectName(_fromUtf8("distr_load_tab_widget"))
        self.distr_load_tab_widget_gl = QtGui.QGridLayout(self.distr_load_tab_widget)
        self.distr_load_tab_widget_gl.setHorizontalSpacing(0)
        self.distr_load_tab_widget_gl.setObjectName(_fromUtf8("distr_load_tab_widget_gl"))
        self.down_distr_load_chkbtn = QtGui.QPushButton(self.distr_load_tab_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.down_distr_load_chkbtn.sizePolicy().hasHeightForWidth())
        self.down_distr_load_chkbtn.setSizePolicy(sizePolicy)
        self.down_distr_load_chkbtn.setMinimumSize(QtCore.QSize(100, 100))
        self.down_distr_load_chkbtn.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.down_distr_load_chkbtn.setFont(font)
        self.down_distr_load_chkbtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.down_distr_load_chkbtn.setCheckable(True)
        self.down_distr_load_chkbtn.setChecked(True)
        self.down_distr_load_chkbtn.setAutoExclusive(True)
        self.down_distr_load_chkbtn.setObjectName(_fromUtf8("down_distr_load_chkbtn"))
        self.distr_load_tab_widget_gl.addWidget(self.down_distr_load_chkbtn, 0, 1, 1, 1)
        self.up_distr_load_chkbtn = QtGui.QPushButton(self.distr_load_tab_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.up_distr_load_chkbtn.sizePolicy().hasHeightForWidth())
        self.up_distr_load_chkbtn.setSizePolicy(sizePolicy)
        self.up_distr_load_chkbtn.setMinimumSize(QtCore.QSize(100, 100))
        self.up_distr_load_chkbtn.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.up_distr_load_chkbtn.setFont(font)
        self.up_distr_load_chkbtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.up_distr_load_chkbtn.setCheckable(True)
        self.up_distr_load_chkbtn.setChecked(False)
        self.up_distr_load_chkbtn.setAutoExclusive(True)
        self.up_distr_load_chkbtn.setObjectName(_fromUtf8("up_distr_load_chkbtn"))
        self.distr_load_tab_widget_gl.addWidget(self.up_distr_load_chkbtn, 0, 0, 1, 1)
        self.lbl_start_distr_load_pos = QtGui.QLabel(self.distr_load_tab_widget)
        self.lbl_start_distr_load_pos.setObjectName(_fromUtf8("lbl_start_distr_load_pos"))
        self.distr_load_tab_widget_gl.addWidget(self.lbl_start_distr_load_pos, 3, 0, 1, 1)
        self.lbl_start_distr_load_mag = QtGui.QLabel(self.distr_load_tab_widget)
        self.lbl_start_distr_load_mag.setObjectName(_fromUtf8("lbl_start_distr_load_mag"))
        self.distr_load_tab_widget_gl.addWidget(self.lbl_start_distr_load_mag, 2, 0, 1, 1)
        self.lbl_end_distr_load_pos = QtGui.QLabel(self.distr_load_tab_widget)
        self.lbl_end_distr_load_pos.setObjectName(_fromUtf8("lbl_end_distr_load_pos"))
        self.distr_load_tab_widget_gl.addWidget(self.lbl_end_distr_load_pos, 5, 0, 1, 1)
        self.lbl_end_distr_load_mag = QtGui.QLabel(self.distr_load_tab_widget)
        self.lbl_end_distr_load_mag.setObjectName(_fromUtf8("lbl_end_distr_load_mag"))
        self.distr_load_tab_widget_gl.addWidget(self.lbl_end_distr_load_mag, 4, 0, 1, 1)
        self.distr_load_start_mag = QtGui.QDoubleSpinBox(self.distr_load_tab_widget)
        self.distr_load_start_mag.setMaximum(999999999.0)
        self.distr_load_start_mag.setProperty("value", 5.0)
        self.distr_load_start_mag.setObjectName(_fromUtf8("distr_load_start_mag"))
        self.distr_load_tab_widget_gl.addWidget(self.distr_load_start_mag, 2, 1, 1, 1)
        self.distr_load_start_pos = QtGui.QDoubleSpinBox(self.distr_load_tab_widget)
        self.distr_load_start_pos.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.distr_load_start_pos.setProperty("value", 1.0)
        self.distr_load_start_pos.setObjectName(_fromUtf8("distr_load_start_pos"))
        self.distr_load_tab_widget_gl.addWidget(self.distr_load_start_pos, 3, 1, 1, 1)
        self.distr_load_end_mag = QtGui.QDoubleSpinBox(self.distr_load_tab_widget)
        self.distr_load_end_mag.setMaximum(999999999.0)
        self.distr_load_end_mag.setProperty("value", 10.0)
        self.distr_load_end_mag.setObjectName(_fromUtf8("distr_load_end_mag"))
        self.distr_load_tab_widget_gl.addWidget(self.distr_load_end_mag, 4, 1, 1, 1)
        self.distr_load_end_pos = QtGui.QDoubleSpinBox(self.distr_load_tab_widget)
        self.distr_load_end_pos.setProperty("value", 5.0)
        self.distr_load_end_pos.setObjectName(_fromUtf8("distr_load_end_pos"))
        self.distr_load_tab_widget_gl.addWidget(self.distr_load_end_pos, 5, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.distr_load_tab_widget_gl.addItem(spacerItem2, 1, 0, 1, 2)
        self.loads_tab.addTab(self.distr_load_tab_widget, _fromUtf8(""))
        self.main_gl.addWidget(self.loads_tab, 2, 2, 4, 1)
        self.verticalLayout.addLayout(self.main_gl)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1239, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuStress_Plot = QtGui.QMenu(self.menubar)
        self.menuStress_Plot.setObjectName(_fromUtf8("menuStress_Plot"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.plot_dock = QtGui.QDockWidget(MainWindow)
        self.plot_dock.setMinimumSize(QtCore.QSize(350, 58))
        self.plot_dock.setObjectName(_fromUtf8("plot_dock"))
        self.plot_dock_contents = QtGui.QWidget()
        self.plot_dock_contents.setObjectName(_fromUtf8("plot_dock_contents"))
        self.plot_dock_contents_vl = QtGui.QVBoxLayout(self.plot_dock_contents)
        self.plot_dock_contents_vl.setMargin(0)
        self.plot_dock_contents_vl.setSpacing(0)
        self.plot_dock_contents_vl.setObjectName(_fromUtf8("plot_dock_contents_vl"))
        self.plots_widget = QtGui.QWidget(self.plot_dock_contents)
        self.plots_widget.setObjectName(_fromUtf8("plots_widget"))
        self.plots_widget_vl = QtGui.QVBoxLayout(self.plots_widget)
        self.plots_widget_vl.setMargin(0)
        self.plots_widget_vl.setSpacing(0)
        self.plots_widget_vl.setObjectName(_fromUtf8("plots_widget_vl"))
        self.plot_dock_contents_vl.addWidget(self.plots_widget)
        self.plot_dock.setWidget(self.plot_dock_contents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.plot_dock)
        self.equations_dock = QtGui.QDockWidget(MainWindow)
        self.equations_dock.setObjectName(_fromUtf8("equations_dock"))
        self.equations_dock_contents = QtGui.QWidget()
        self.equations_dock_contents.setObjectName(_fromUtf8("equations_dock_contents"))
        self.equations_dock_contents_vl = QtGui.QVBoxLayout(self.equations_dock_contents)
        self.equations_dock_contents_vl.setMargin(0)
        self.equations_dock_contents_vl.setObjectName(_fromUtf8("equations_dock_contents_vl"))
        self.equations_lbl = QtGui.QTextBrowser(self.equations_dock_contents)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria"))
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.equations_lbl.setFont(font)
        self.equations_lbl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.equations_lbl.setObjectName(_fromUtf8("equations_lbl"))
        self.equations_dock_contents_vl.addWidget(self.equations_lbl)
        self.equations_dock.setWidget(self.equations_dock_contents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.equations_dock)
        self.tool_bar = QtGui.QToolBar(MainWindow)
        self.tool_bar.setObjectName(_fromUtf8("tool_bar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.tool_bar)
        self.actionDisplay_Stress_Value = QtGui.QAction(MainWindow)
        self.actionDisplay_Stress_Value.setCheckable(True)
        self.actionDisplay_Stress_Value.setObjectName(_fromUtf8("actionDisplay_Stress_Value"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionQuit)
        self.menuStress_Plot.addAction(self.actionDisplay_Stress_Value)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuStress_Plot.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.loads_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.young_module_dpsn, self.length_dspn)
        MainWindow.setTabOrder(self.length_dspn, self.left_support_combo)
        MainWindow.setTabOrder(self.left_support_combo, self.right_support_combo)
        MainWindow.setTabOrder(self.right_support_combo, self.calculate_beam)
        MainWindow.setTabOrder(self.calculate_beam, self.supports_combo)
        MainWindow.setTabOrder(self.supports_combo, self.remove_support_btn)
        MainWindow.setTabOrder(self.remove_support_btn, self.hinges_combo)
        MainWindow.setTabOrder(self.hinges_combo, self.remove_hinge_btn)
        MainWindow.setTabOrder(self.remove_hinge_btn, self.loads_tab)
        MainWindow.setTabOrder(self.loads_tab, self.pnt_load_up_chkbtn)
        MainWindow.setTabOrder(self.pnt_load_up_chkbtn, self.pnt_load_down_chkbtn)
        MainWindow.setTabOrder(self.pnt_load_down_chkbtn, self.pnt_load_mag_dpsn)
        MainWindow.setTabOrder(self.pnt_load_mag_dpsn, self.pnt_load_pos_dpsn)
        MainWindow.setTabOrder(self.pnt_load_pos_dpsn, self.moment_ccw_chkbtn)
        MainWindow.setTabOrder(self.moment_ccw_chkbtn, self.moment_cw_chkbtn)
        MainWindow.setTabOrder(self.moment_cw_chkbtn, self.moment_mag_dpsn)
        MainWindow.setTabOrder(self.moment_mag_dpsn, self.moment_pos_dpsn)
        MainWindow.setTabOrder(self.moment_pos_dpsn, self.up_distr_load_chkbtn)
        MainWindow.setTabOrder(self.up_distr_load_chkbtn, self.down_distr_load_chkbtn)
        MainWindow.setTabOrder(self.down_distr_load_chkbtn, self.distr_load_start_mag)
        MainWindow.setTabOrder(self.distr_load_start_mag, self.distr_load_start_pos)
        MainWindow.setTabOrder(self.distr_load_start_pos, self.distr_load_end_mag)
        MainWindow.setTabOrder(self.distr_load_end_mag, self.distr_load_end_pos)
        MainWindow.setTabOrder(self.distr_load_end_pos, self.add_load_btn)
        MainWindow.setTabOrder(self.add_load_btn, self.remove_load_btn)
        MainWindow.setTabOrder(self.remove_load_btn, self.load_treeview)
        MainWindow.setTabOrder(self.load_treeview, self.equations_lbl)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BeamPy ", None))
        self.beam_widget.setStatusTip(_translate("MainWindow", "Beam Display", None))
        self.message_lbl.setStatusTip(_translate("MainWindow", "Current BeamPy message", None))
        self.message_lbl.setText(_translate("MainWindow", "Ready", None))
        self.lbl_message.setText(_translate("MainWindow", "Message:", None))
        self.calculate_beam.setStatusTip(
            _translate("MainWindow", "Solves the differential equations and plot diagrams (F5)", None))
        self.calculate_beam.setText(_translate("MainWindow", "Solve", None))
        self.calculate_beam.setShortcut(_translate("MainWindow", "F5", None))
        self.beam_properties_gb.setTitle(_translate("MainWindow", "Beam Properties", None))
        self.base_dspn.setStatusTip(_translate("MainWindow", "Beam section Base", None))
        self.pushButton.setText(_translate("MainWindow", "T", None))
        self.pushButton_3.setText(_translate("MainWindow", "I", None))
        self.pushButton_2.setText(_translate("MainWindow", "l", None))
        self.lbl_length.setText(_translate("MainWindow", "Length (m)", None))
        self.lbl_young_module.setText(_translate("MainWindow", "E (GPa)", None))
        self.length_dspn.setStatusTip(_translate("MainWindow", "Beam Length", None))
        self.young_module_dpsn.setStatusTip(_translate("MainWindow", "Beam Young Modulus", None))
        self.height_dpsn.setStatusTip(_translate("MainWindow", "Beam section Height", None))
        self.lbl_inertia_moment.setText(_translate("MainWindow", "Inertia (m^4)", None))
        self.lbl_height.setText(_translate("MainWindow", "Height (m)", None))
        self.lbl_length_2.setText(_translate("MainWindow", "Base (m)", None))
        self.inertia_moment_dspn.setText(_translate("MainWindow", "0,0000", None))
        self.supports_gb.setTitle(_translate("MainWindow", "Supports", None))
        self.supports_combo.setStatusTip(
            _translate("MainWindow", "Type support pos. then press Enter to add a Support", None))
        self.left_support_combo.setItemText(0, _translate("MainWindow", "Simply", None))
        self.left_support_combo.setItemText(1, _translate("MainWindow", "Fixed", None))
        self.left_support_combo.setItemText(2, _translate("MainWindow", "Free", None))
        self.lbl_right_support.setText(_translate("MainWindow", "Right Support", None))
        self.right_support_combo.setItemText(0, _translate("MainWindow", "Simply", None))
        self.right_support_combo.setItemText(1, _translate("MainWindow", "Fixed", None))
        self.right_support_combo.setItemText(2, _translate("MainWindow", "Free", None))
        self.lbl_add_support_2.setText(_translate("MainWindow", "Add Hinges", None))
        self.hinges_combo.setStatusTip(
            _translate("MainWindow", "Type hinge pos. then press Enter to add a Hinge", None))
        self.remove_hinge_btn.setStatusTip(_translate("MainWindow", "Removes selected Hinge (Ctrl + H)", None))
        self.remove_hinge_btn.setText(_translate("MainWindow", "Remove Hinge", None))
        self.remove_hinge_btn.setShortcut(_translate("MainWindow", "Ctrl+H", None))
        self.lbl_left_support.setText(_translate("MainWindow", "Left Support", None))
        self.lbl_add_support.setText(_translate("MainWindow", "Add Supports", None))
        self.remove_support_btn.setStatusTip(_translate("MainWindow", "Removes selected Support (Ctrl + S)", None))
        self.remove_support_btn.setText(_translate("MainWindow", "Remove Support", None))
        self.remove_support_btn.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.add_load_btn.setStatusTip(_translate("MainWindow", "Adds Load or Moment (Enter)", None))
        self.add_load_btn.setText(_translate("MainWindow", "Add", None))
        self.remove_load_btn.setStatusTip(_translate("MainWindow", "Removes an item from the list  (Del)", None))
        self.remove_load_btn.setText(_translate("MainWindow", "Remove", None))
        self.remove_load_btn.setShortcut(_translate("MainWindow", "Del", None))
        self.load_treeview.setStatusTip(_translate("MainWindow", "Beam loaded Items", None))
        self.lbl_point_load_mag.setText(_translate("MainWindow", "Load Magnitude:", None))
        self.lbl_point_load_pos.setText(_translate("MainWindow", "Load Position: ", None))
        self.pnt_load_up_chkbtn.setText(_translate("MainWindow", "↑", None))
        self.pnt_load_down_chkbtn.setText(_translate("MainWindow", "↓", None))
        self.loads_tab.setTabText(self.loads_tab.indexOf(self.pnt_load_tab_widget), _translate("MainWindow", "Point Load", None))
        self.lbl_moment_pos.setText(_translate("MainWindow", "Moment Magnitude:", None))
        self.lbl_moment_mag.setText(_translate("MainWindow", "Moment Position: ", None))
        self.moment_ccw_chkbtn.setText(_translate("MainWindow", "↺", None))
        self.moment_cw_chkbtn.setText(_translate("MainWindow", "↻", None))
        self.loads_tab.setTabText(self.loads_tab.indexOf(self.moment_tab_widget), _translate("MainWindow", "Moment", None))
        self.down_distr_load_chkbtn.setText(_translate("MainWindow", "↓", None))
        self.up_distr_load_chkbtn.setText(_translate("MainWindow", "↑", None))
        self.lbl_start_distr_load_pos.setText(_translate("MainWindow", "Start Position: ", None))
        self.lbl_start_distr_load_mag.setText(_translate("MainWindow", "Start Magnitude:", None))
        self.lbl_end_distr_load_pos.setText(_translate("MainWindow", "End Position: ", None))
        self.lbl_end_distr_load_mag.setText(_translate("MainWindow", "End Magnitude:", None))
        self.loads_tab.setTabText(self.loads_tab.indexOf(self.distr_load_tab_widget),
                                  _translate("MainWindow", "Distr. Load", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuStress_Plot.setTitle(_translate("MainWindow", "Stress Plot", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.plot_dock.setWindowTitle(_translate("MainWindow", "Shear, bending, angle and displacement diagrams", None))
        self.equations_dock.setWindowTitle(_translate("MainWindow", "Equations", None))
        self.equations_lbl.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
                                                            "</style></head><body style=\" font-family:\'Cambria\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Times New Roman\'; font-size:14pt;\"><br /></p></body></html>",
                                              None))
        self.tool_bar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionDisplay_Stress_Value.setText(_translate("MainWindow", "Display Stress Value", None))
        self.actionDisplay_Stress_Value.setShortcut(_translate("MainWindow", "D", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+W", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

